<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateGedmiUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('gedmi_user', function (Blueprint $table) {
            $table->id();
            $table->string('username')->unique();
            $table->string('password');
            $table->string('role');
            $table->timestamps();
        });

        $defaultData = [
            [
                'id' => 1,
                'username' => 'admin123',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'username' => 'kepalasekolah',
                'password' => 'kepsek111',
                'role' => 'kepalasekolah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'username' => 'agung',
                'password' => 'agung123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'username' => 'almas',
                'password' => 'almas123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'username' => 'diana',
                'password' => 'diana123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'username' => 'erlina',
                'password' => 'erlina123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'username' => 'gaya',
                'password' => 'gaya123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'username' => 'hengki',
                'password' => 'hengki123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'username' => 'intan',
                'password' => 'intan123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'username' => 'jessica',
                'password' => 'jessica123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'username' => 'keti',
                'password' => 'keti123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'username' => 'sabdana',
                'password' => 'sabdana123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 13,
                'username' => 'salamauddin',
                'password' => 'salamuddin123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'username' => 'siti',
                'password' => 'siti123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'username' => 'tatang',
                'password' => 'tatang123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'username' => 'venny',
                'password' => 'venny123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'username' => 'purba',
                'password' => 'purba123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 18,
                'username' => '21288090',
                'password' => '21288090',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'username' => '21288091',
                'password' => '21288091',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'username' => '21288092',
                'password' => '21288092',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'username' => '21288093',
                'password' => '21288093',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'username' => '21288094',
                'password' => '21288094',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'username' => '21288095',
                'password' => '21288095',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'username' => '21288096',
                'password' => '21288096',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'username' => '21288097',
                'password' => '21288097',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'username' => '21288098',
                'password' => '21288098',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'username' => '21288099',
                'password' => '21288099',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'username' => '21288100',
                'password' => '21288100',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'username' => '21288101',
                'password' => '21288101',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'username' => '21288102',
                'password' => '21288102',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'username' => '21288103',
                'password' => '21288103',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'username' => '21288104',
                'password' => '21288104',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'username' => '21288105',
                'password' => '21288105',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'username' => '21288106',
                'password' => '21288106',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'username' => '21288107',
                'password' => '21288107',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'username' => '21288108',
                'password' => '21288108',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'username' => '21288109',
                'password' => '21288109',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'username' => '20259180',
                'password' => '20259180',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 39,
                'username' => '20259181',
                'password' => '20259181',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'username' => '20259182',
                'password' => '20259182',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'username' => '20259183',
                'password' => '20259183',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'username' => '20259184',
                'password' => '20259184',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'username' => '20259185',
                'password' => '20259185',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'username' => '20259186',
                'password' => '20259186',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'username' => '20259187',
                'password' => '20259187',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'username' => '20259188',
                'password' => '20259188',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'username' => '20259189',
                'password' => '20259189',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'username' => '20259190',
                'password' => '20259190',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'username' => '20259191',
                'password' => '20259191',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'username' => '20259192',
                'password' => '20259192',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'username' => '20259193',
                'password' => '20259193',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'username' => '20259194',
                'password' => '20259194',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 53,
                'username' => '20259195',
                'password' => '20259195',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'username' => '20259196',
                'password' => '20259196',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'username' => '20259197',
                'password' => '20259197',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'username' => '20259198',
                'password' => '20259198',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'username' => '20259199',
                'password' => '20259199',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id' => 58,
                'username' => '19212941',
                'password' => '19212941',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'username' => '19212942',
                'password' => '19212942',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'username' => '19212943',
                'password' => '19212943',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'username' => '19212944',
                'password' => '19212944',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'username' => '19212945',
                'password' => '19212945',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'username' => '19212946',
                'password' => '19212946',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'username' => '19212947',
                'password' => '19212947',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'username' => '19212948',
                'password' => '19212948',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'username' => '19212949',
                'password' => '19212949',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'username' => '19212950',
                'password' => '19212950',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'username' => '19212951',
                'password' => '19212951',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'username' => '19212952',
                'password' => '19212952',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'username' => '19212953',
                'password' => '19212953',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'username' => '19212954',
                'password' => '19212954',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'username' => '19212955',
                'password' => '19212955',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'username' => '19212956',
                'password' => '19212956',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'username' => '19212957',
                'password' => '19212957',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'username' => '19212958',
                'password' => '19212958',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'username' => '19212959',
                'password' => '19212959',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'username' => '19212960',
                'password' => '19212960',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('gedmi_user')->insert($defaultData);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('gedmi_user');
    }
}
