<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDediLatihanTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
       Schema::create('dedi_latihan', function (Blueprint $table) {
            $table->id();
            $table->integer('id_mapel');
            $table->text('soal');
            $table->string('jawaban_beneran', );
            $table->string('pilihan_jawaban1', );
            $table->string('pilihan_jawaban2', );
            $table->string('pilihan_jawaban3', );
            $table->timestamps();
        });

        $defaulData = [
            [
                'id' => 1,
                'id_mapel' => 1,
                'soal' => 'Mikroorganisme adalah' ,
                'jawaban_beneran' => 'Makhluk kecil yang hanya dapat dilihat dengan bantuan Mikroskop',
                'pilihan_jawaban1' => 'Makhluk kecil yang dapat dilihat dengan kasat mata',
                'pilihan_jawaban2' => 'Makhluk Besar yang dapat dilihat',
                'pilihan_jawaban3' => 'Sejenis Parasit',

            ],
            [
                'id' => 2,
                'id_mapel' => 1,
                'soal' => 'Satuan pada Mikroorganisme adalah',
                'jawaban_beneran' => 'Micron',
                'pilihan_jawaban1' => 'Meter',
                'pilihan_jawaban2' => 'Gram',
                'pilihan_jawaban3' => "Kilo",

            ],
            [
                'id' => 3,
                'id_mapel' => 1,
                'soal' => 'Siapakah penemu Mikroskop',
                'jawaban_beneran' => 'Antonio van Leeuwenhock',
                'pilihan_jawaban1' => 'Louis Pasteur',
                'pilihan_jawaban2' => 'Robert van de Vaart',
                'pilihan_jawaban3' => 'Robert Koch',

            ],
            [
                'id' => 4,
                'id_mapel' => 1,
                'soal' => 'Siapakah Penemu dari Penyakit Tuberculosis',
                'jawaban_beneran' => 'Robert Koch',
                'pilihan_jawaban1' => 'Robert Van de Vaart',
                'pilihan_jawaban2' => 'Louis Pasteur',
                'pilihan_jawaban3' => 'Antonio van Leeuwenhock',

            ],
            [
                'id' => 5,
                'id_mapel' => 1,
                'soal' => 'Siapakah Penemu dari Penyakit Tuberculosis',
                'jawaban_beneran' => 'Robert Koch',
                'pilihan_jawaban1' => 'Robert Van de Vaart',
                'pilihan_jawaban2' => 'Louis Pasteur',
                'pilihan_jawaban3' => 'Antonio van Leeuwenhock',

            ],
            [
                'id' => 6,
                'id_mapel' => 1,
                'soal' => 'Bakteri Berbentuk Bulat disebut',
                'jawaban_beneran' => 'Coccus',
                'pilihan_jawaban1' => 'Basil',
                'pilihan_jawaban2' => 'Spiral',
                'pilihan_jawaban3' => 'Streptobasil',

            ],
            [
                'id' => 7,
                'id_mapel' => 1,
                'soal' => 'Bakteri yang berbentuk seperti buah anggur adalah',
                'jawaban_beneran' => 'Staphylococcus',
                'pilihan_jawaban1' => 'Streptococcus',
                'pilihan_jawaban2' => 'Diplococcus',
                'pilihan_jawaban3' => 'Tetracoccus',

            ],
            [
                'id' => 8,
                'id_mapel' => 1,
                'soal' => 'Berikut ini macam macam dari pewarnaan bakteri,Kecuali ',
                'jawaban_beneran' => 'Pewarnaan Kilat',
                'pilihan_jawaban1' => 'Pewarnaan Sederhana',
                'pilihan_jawaban2' => 'Pewarnaan Negatif',
                'pilihan_jawaban3' => 'Pewarnaan Gram',

            ],
            [
                'id' => 9,
                'id_mapel' => 1,
                'soal' => 'Dibawah ini adalah tujuan dari pewarnaan Bakteri Kecuali :',
                'jawaban_beneran' => 'Mengembangkan Bakteri',
                'pilihan_jawaban1' => 'Membantu identifikasi Bakteri',
                'pilihan_jawaban2' => 'Mengamati Morfologi Bakteri',
                'pilihan_jawaban3' => 'Membedakan organisme yag serupa',

            ],
            [
                'id' => 10,
                'id_mapel' => 1,
                'soal' => 'Pada Pewarnaan Negatif Regensia apa yang digunakan ?',
                'jawaban_beneran' => 'Tinta Cina',
                'pilihan_jawaban1' => 'Fuchsin',
                'pilihan_jawaban2' => 'Gram',
                'pilihan_jawaban3' => 'Carbol',

            ],
            [
                'id' => 11,
                'id_mapel' => 1,
                'soal' => 'Pada Pewarnaan Gram ada golongan apa saja ',
                'jawaban_beneran' => 'Gram Positif dan Gram Negatif',
                'pilihan_jawaban1' => 'Gram Positif',
                'pilihan_jawaban2' => 'Gram Negatif',
                'pilihan_jawaban3' => 'Gram Plus',

            ],
            [
                'id' => 12,
                'id_mapel' => 1,
                'soal' => 'Pada Regensia Karbol Gentian Violet memiliki komposisi bubuk kristal gentian violet sebanyak  ',
                'jawaban_beneran' => '5 Gram',
                'pilihan_jawaban1' => '4 Gram',
                'pilihan_jawaban2' => '6 Gram',
                'pilihan_jawaban3' => '10 Gram',

            ],
            [
                'id' => 13,
                'id_mapel' => 1,
                'soal' => 'Pada Pemeriksaan Basil Tahan Asam Menggunakan Sampel',
                'jawaban_beneran' => 'Sputum',
                'pilihan_jawaban1' => 'Darah',
                'pilihan_jawaban2' => 'Nanah',
                'pilihan_jawaban3' => 'Faeses',

            ],
            [
                'id' => 14,
                'id_mapel' => 1,
                'soal' => 'Untuk Pemeriksaan Basil Tahan Asam Dilakukan Dengan Cara',
                'jawaban_beneran' => 'Pewarnaan Ziehl Neelsen',
                'pilihan_jawaban1' => 'Pewarnaan Gram',
                'pilihan_jawaban2' => 'Pewarnaan Sederhana',
                'pilihan_jawaban3' => 'Pewarnaan Negatif',

            ],
            [
                'id' => 15,
                'id_mapel' => 1,
                'soal' => 'Dibawah ini Fungsi Dari Fiksasi Kecuali',
                'jawaban_beneran' => 'Mengembangbiakan Bakteri',
                'pilihan_jawaban1' => 'Mencegah globula-globula protein sel',
                'pilihan_jawaban2' => 'Merubah afinitas daya lengkat cat',
                'pilihan_jawaban3' => 'Dapat membunuh bakteri secara cepat tanpa menyebakan perubahan bentuk dan strukturnya',

            ],
            [
                'id' => 16,
                'id_mapel' => 1,
                'soal' => 'Pada Melakukan Pewarnaan Sampel Apakah yang digunakaan',
                'jawaban_beneran' => 'Biakan Dalam Bouillon',
                'pilihan_jawaban1' => 'Sputum',
                'pilihan_jawaban2' => 'Tinja',
                'pilihan_jawaban3' => 'Darah',

            ],
            [
                'id' => 17,
                'id_mapel' => 1,
                'soal' => 'Syarat-syarat pembenihan Media Adalah',
                'jawaban_beneran' => 'Steril dan Ph yang disesuaikan dengan pertumbuhan bakteri',
                'pilihan_jawaban1' => 'Asam yang tinggi',
                'pilihan_jawaban2' => 'Makanan bakteri yang sedikit',
                'pilihan_jawaban3' => 'Zat-zat yang menghambat pertumbuhan bakteri',

            ],[
                'id' => 18,
                'id_mapel' => 1,
                'soal' => '.Pada Lensa Berapakah untuk melihat sampel dari bakteri',
                'jawaban_beneran' => '100 x',
                'pilihan_jawaban1' => '10 x',
                'pilihan_jawaban2' => '50 x',
                'pilihan_jawaban3' => '1000 x',

            ],
            [
                'id' => 19,
                'id_mapel' => 1,
                'soal' => 'Pada Pewarnaan Sederhana Menggunakan Regensia',
                'jawaban_beneran' => 'Fuchsin 0,5 gram',
                'pilihan_jawaban1' => 'Fuchsin 0,1 gram',
                'pilihan_jawaban2' => 'Carbol Gentian Violet 0,5%',
                'pilihan_jawaban3' => 'Tinta Cina',

            ],
            [
                'id' => 20,
                'id_mapel' => 1,
                'soal' => 'Apakah Tujuan Pewarnaan dari pewaraan Ziehl Neelsen',
                'jawaban_beneran' => 'Untuk Melihat Bakteri tahan asam dalam bahan pemeriksaan',
                'pilihan_jawaban1' => 'Untuk Melihat latar belakang warna',
                'pilihan_jawaban2' => 'Untuk Membiakaan Bakteri',
                'pilihan_jawaban3' => 'Untuk membuat media',

            ],
            [
                'id' => 21,
                'id_mapel' => 1,
                'soal' => 'Pada pewarnaan Gram,bila di Mikroskop ditemukan bakteri bewarna ungu maka,',
                'jawaban_beneran' => 'Bakteri bersifat Gram Positif',
                'pilihan_jawaban1' => 'Bakteri bersifat Gram Negatif',
                'pilihan_jawaban2' => 'Bakteri bersifat Gram Positif dan Gram Negatif',
                'pilihan_jawaban3' => 'Bakteri Tidak memiliki Sifat',

            ],
            [
                'id' => 22,
                'id_mapel' => 2,
                'soal' => 'Volume Plasma darah normal berkisar ….% dari berat badan ',
                'jawaban_beneran' => '5%',
                'pilihan_jawaban1' => '4%',
                'pilihan_jawaban2' => '3%',
                'pilihan_jawaban3' => '6%',

            ],
            [
                'id' => 23,
                'id_mapel' => 2,
                'soal' => 'Ilmu yang mempelajari tentang darah, baik mengenai fungsi, susunan dan penyakit-penyakit yang berhubungan darah disebut ',
                'jawaban_beneran' => 'Hematologi',
                'pilihan_jawaban1' => 'Hemoglobin',
                'pilihan_jawaban2' => 'Haemoposis',
                'pilihan_jawaban3' => 'Hematokrit',

            ],
            [
                'id' => 24,
                'id_mapel' => 2,
                'soal' => 'Plasma Darah adalah ',
                'jawaban_beneran' => 'Darah dikurang sel-sel darah',
                'pilihan_jawaban1' => 'Plasma ditambah fibrinogen',
                'pilihan_jawaban2' => 'Plasma dikurang fibrinogen',
                'pilihan_jawaban3' => 'Darah ditambah sel-sel darah',

            ],
            [
                'id' => 25,
                'id_mapel' => 2,
                'soal' => 'Yang tidak termasuk fungsi plasma protein adalah : ',
                'jawaban_beneran' => 'Digunakan sebagai fagosit',
                'pilihan_jawaban1' => 'sebagai antibodi',
                'pilihan_jawaban2' => 'sebagai buffer dalam darah',
                'pilihan_jawaban3' => 'mempertahankan tekanan osmosis koloid',

            ],
            [
                'id' => 26,
                'id_mapel' => 2,
                'soal' => 'Bahan yang tidak dibawa dalam transportasi oleh darah adalah ',
                'jawaban_beneran' => 'Elektrolit',
                'pilihan_jawaban1' => 'Air',
                'pilihan_jawaban2' => 'Hormon',
                'pilihan_jawaban3' => 'Oksigen',

            ],
            [
                'id' => 27,
                'id_mapel' => 2,
                'soal' => 'Cairan darah yang diperoleh tanpa pemberian antikoagulan dinamakan ',
                'jawaban_beneran' => 'Serum',
                'pilihan_jawaban1' => 'Plasma',
                'pilihan_jawaban2' => 'Cholestrol',
                'pilihan_jawaban3' => 'Protein',

            ],
            [
                'id' => 28,
                'id_mapel' => 2,
                'soal' => 'Sel Leukosit berguna untuk melawan kuman-kuman yang masuk ke dalam tubuh dan untuk merangsang pembentukan antibody hal ini termasuk fungsi darah dalam proses ',
                'jawaban_beneran' => 'Imunitas',
                'pilihan_jawaban1' => 'Nutrisi',
                'pilihan_jawaban2' => 'Ekskreasi',
                'pilihan_jawaban3' => 'Respirasi',

            ],
            [
                'id' => 29,
                'id_mapel' => 2,
                'soal' => 'Suatu Cairan yang terdapat di dalam pembuluh-pembuluh dan terdapat benda-benda padat yang melayang-layang didalam nya disebut ',
                'jawaban_beneran' => 'Darah',
                'pilihan_jawaban1' => 'Serum',
                'pilihan_jawaban2' => 'Plasma',
                'pilihan_jawaban3' => "Hematokrit",

            ],
            [
                'id' => 30,
                'id_mapel' => 2,
                'soal' => 'Yang tidak termasuk komponen koupuskuli adalah : ',
                'jawaban_beneran' => 'Plasma',
                'pilihan_jawaban1' => 'Leukosit',
                'pilihan_jawaban2' => 'Eritrosit',
                'pilihan_jawaban3' => 'Trombosit',

            ],
            [
                'id' => 31,
                'id_mapel' => 2,
                'soal' => 'Pengambilan darah kapiler pada belita berada di',
                'jawaban_beneran' => 'Tumit Kaki',
                'pilihan_jawaban1' => 'Jari Manis Tangan',
                'pilihan_jawaban2' => 'Ibu Jari Tangan',
                'pilihan_jawaban3' => 'Anak Daun Telinga',

            ],
            [
                'id' => 32,
                'id_mapel' => 2,
                'soal' => 'Alat untuk mengambil darah kapiler adalah, kecuali : ',
                'jawaban_beneran' => 'Spoit 3ml',
                'pilihan_jawaban1' => 'Lancet',
                'pilihan_jawaban2' => 'Pipet HB',
                'pilihan_jawaban3' => 'Kapas Alkohol',

            ],
            [
                'id' => 33,
                'id_mapel' => 2,
                'soal' => 'Lokasi Pengambilan darah vena pada orang dewasa adalah : ',
                'jawaban_beneran' => 'Vena mediana cubiti',
                'pilihan_jawaban1' => 'Vena sinus sagitalis',
                'pilihan_jawaban2' => 'Vena jugularis externa',
                'pilihan_jawaban3' => 'Vena Femolaris',

            ],
            [
                'id' => 34,
                'id_mapel' => 2,
                'soal' => 'Alat-alat yang digunakan untuk darah vena kecuali : ',
                'jawaban_beneran' =>  'Pipet Hb',
                'pilihan_jawaban1' => 'Spuit Streil',
                'pilihan_jawaban2' => 'Karet Pengebat',
                'pilihan_jawaban3' => 'Kapas Alkohol',

            ],
            [
                'id' => 35,
                'id_mapel' => 2,
                'soal' => 'Darah Kapiler dapat digunakan untuk pemeriksaan : ',
                'jawaban_beneran' => 'Hemaglobin',
                'pilihan_jawaban1' => 'Darah Rutin',
                'pilihan_jawaban2' => 'Laju Endap Darah',
                'pilihan_jawaban3' => 'Waktu Pembekuan Darah',

            ],
            [
                'id' => 36,
                'id_mapel' => 2,
                'soal' => 'Yang tidak merupakan kontrak indikasi pada pengambilan darah kapiler : ',
                'jawaban_beneran' => 'Menggunakan Alat Stril',
                'pilihan_jawaban1' => 'Oedem',
                'pilihan_jawaban2' => 'Dermatitis',
                'pilihan_jawaban3' => 'Bekas Luka',

            ],
            [
                'id' => 37,
                'id_mapel' => 2,
                'soal' => 'Salah satu kesalahan pengambilan darah kapiler adalah, kecuali ',
                'jawaban_beneran' => 'Tetesan Pertama dibuang',
                'pilihan_jawaban1' => 'Tusukan kurang dalam',
                'pilihan_jawaban2' => 'Tusukan Berulang-ulang',
                'pilihan_jawaban3' => 'Tusukan terlalu dalam',

            ],
            [
                'id' => 38,
                'id_mapel' => 2,
                'soal' => 'Salah satu kesalahan pengambilan darah vena adalah : ',
                'jawaban_beneran' =>  'Menggunakan laricet',
                'pilihan_jawaban1' => 'Menggunakan kapas alkohol',
                'pilihan_jawaban2' => 'Menggunakan Spuit streil',
                'pilihan_jawaban3' => 'Menggunakan botol antikoagulan',

            ],
            [
                'id' => 39,
                'id_mapel' => 2,
                'soal' => 'Pemeriksaan Hematologi menggunakan darah vena adalah kecuali : ',
                'jawaban_beneran' =>  'Waktu pendarahan',
                'pilihan_jawaban1' => 'Darah rutin',
                'pilihan_jawaban2' => 'Golongan Darah',
                'pilihan_jawaban3' => 'Waktu Pembekuan Darah',

            ],
            [
                'id' => 40,
                'id_mapel' => 2,
                'soal' => 'Persiapan Dalam pengambilan darah yang tidak benar adalah :',
                'jawaban_beneran' => 'Analis gugup dan Ketakutan',
                'pilihan_jawaban1' => 'Pasien dalam keadaan tenang',
                'pilihan_jawaban2' => 'Pasien sebaiknya dalam keadaan berbaring',
                'pilihan_jawaban3' => 'alat sudah di persiapkan',

            ],
            [
                'id' => 41,
                'id_mapel' => 3,
                'soal' => 'Cara Pengambilan bahan pemeriksaan urine yang dianjurkan untuk pemeriksaan lab adalah',
                'jawaban_beneran' => 'Sewaktu-waktu',
                'pilihan_jawaban1' => 'Jam 12 siang',
                'pilihan_jawaban2' => 'Pada Sore hari',
                'pilihan_jawaban3' => 'Porsi Tengah',

            ],
            [
                'id' => 42,
                'id_mapel' => 3,
                'soal' => 'Berikut ini faktor-faktor yang mempengaruhi produksi urine kecuali,',
                'jawaban_beneran' => 'Berat Badan',
                'pilihan_jawaban1' => 'Cuaca',
                'pilihan_jawaban2' => 'Makanan dan Minuman',
                'pilihan_jawaban3' => 'Lamanya Waktu Tidur',

            ],
            [
                'id' => 43,
                'id_mapel' => 3,
                'soal' => 'Urine yang pertama kali keluar di buang, urine yang keluar kemudian di tampung dan urine yang terakhir dibuang.Urine yang dikumpulkan dengan cara tersebut disebut',
                'jawaban_beneran' =>  'Midstream',
                'pilihan_jawaban1' => 'Acak',
                'pilihan_jawaban2' => 'Sewaktu',
                'pilihan_jawaban3' => 'Kateterisasi',

            ],
            [
                'id' => 44,
                'id_mapel' => 3,
                'soal' => 'Cara yang benar untuk memperoleh bahan pemeriksaan urine pada penderita yang sedang haid adalah sebagai berikut',
                'jawaban_beneran' =>  'Clean Voickel specimen',
                'pilihan_jawaban1' => 'Midstream',
                'pilihan_jawaban2' => 'Fungsi suprapubik',
                'pilihan_jawaban3' => 'Kateterisasi',

            ],[
                'id' => 45,
                'id_mapel' => 3,
                'soal' => 'Cara yang benar untuk memperoleh bahan pemisahan urine untuk pemeriksaan bakteriologis adalah',
                'jawaban_beneran' =>  'Midstream',
                'pilihan_jawaban1' => 'Katerterisasi',
                'pilihan_jawaban2' => 'Nocther',
                'pilihan_jawaban3' => 'Fungsi Suprapubik',

            ],
            [
                'id' => 46,
                'id_mapel' => 3,
                'soal' => 'Pengawet Urine formalidhida tidak bisa digunakan untuk mengawetkan urine yang mengandung glukosa karena, ',
                'jawaban_beneran' =>  'Mereduksi Glukosa',
                'pilihan_jawaban1' => 'Mereduksi gugus keton',
                'pilihan_jawaban2' => 'Mengoksidasi Cu',
                'pilihan_jawaban3' => 'Mengoksidasi gugus Keton',

            ],
            [
                'id' => 47,
                'id_mapel' => 3,
                'soal' => 'Syarat wadah yang baik untuk menampung urine adalah',
                'jawaban_beneran' =>  'Terbuat dari kaca/plastik yang tidak tembus cahaya dengan mulut yang lebar dan mempunyai penutup',
                'pilihan_jawaban1' => 'Terbuat dari kaca/plastik yang tembus cahaya',
                'pilihan_jawaban2' => 'Terbuat dari kaca/plastik tanpa penutup',
                'pilihan_jawaban3' => 'Terbuat dari kaca/plastik yang bermulut kecil',

            ],
            [
                'id' => 48,
                'id_mapel' => 3,
                'soal' => 'Thymol dalam bentuk hablur 50mg sangat baik untuk mengawetkan urine',
                'jawaban_beneran' => '100 ml',
                'pilihan_jawaban1' => '10 ml',
                'pilihan_jawaban2' => '150 ml',
                'pilihan_jawaban3' => '50 ml',

            ],
            [
                'id' => 49,
                'id_mapel' => 3,
                'soal' => 'Pengawet yang mempunyai sifat pengawet all round ialah',
                'jawaban_beneran' =>  'Na2CO3',
                'pilihan_jawaban1' => 'H2SO4',
                'pilihan_jawaban2' => 'Tymol',
                'pilihan_jawaban3' => 'Toluena',

            ],
            [
                'id' => 50,
                'id_mapel' => 3,
                'soal' => 'Urine Yang di kumpulkan dari jam 7 pagi sampai jam 7 malam disebut',
                'jawaban_beneran' =>  'Urine Siang 12 jam',
                'pilihan_jawaban1' => 'Urine Malam 12 jam',
                'pilihan_jawaban2' => 'Urine 24 Jam',
                'pilihan_jawaban3' => 'Urine Pagi',

            ],
            [
                'id' => 51,
                'id_mapel' => 3,
                'soal' => 'Organ ginjal manusia terdiri dari',
                'jawaban_beneran' =>  '2 pasang Ginjal',
                'pilihan_jawaban1' => '1 pasang Ginjal',
                'pilihan_jawaban2' => '3 pasang Ginjal',
                'pilihan_jawaban3' => '5 pasang Ginjal',

            ],
            [
                'id' => 52,
                'id_mapel' => 3,
                'soal' => 'Proses filtrasi dalam pembentukan urine terjadi di daerah',
                'jawaban_beneran' =>  'Glomerulos',
                'pilihan_jawaban1' => 'Ureter',
                'pilihan_jawaban2' => 'Tubulus',
                'pilihan_jawaban3' => 'Ansa Henle',

            ],
            [
                'id' => 53,
                'id_mapel' => 3,
                'soal' => 'Proses reabsorbsi dalam pembentukan urine terjadi di daerah',
                'jawaban_beneran' =>  'Tubulus',
                'pilihan_jawaban1' => 'Ureter',
                'pilihan_jawaban2' => 'Glomerulos',
                'pilihan_jawaban3' => 'Ansa Henle',

            ],
            [
                'id' => 54,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Protein urine apabila urine berubah warna menjadi sangat keruh serta ada endapan yang mengumpul, maka hasil diagnosa tersebut ialah',
                'jawaban_beneran' => 'Positif 4',
                'pilihan_jawaban1' => 'Positif 1',
                'pilihan_jawaban2' => 'Positif 2',
                'pilihan_jawaban3' => 'Positif 3',

            ],
            [
                'id' => 55,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Protein Urine Regensia apakah yang digunakan',
                'jawaban_beneran' => 'Asam Asetat 6%',
                'pilihan_jawaban1' => 'Asam Aseton 6%',
                'pilihan_jawaban2' => 'Benedict',
                'pilihan_jawaban3' => 'Amonia',

            ],
            [
                'id' => 56,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Reduksi urine bila dinyatakan positif 2,maka pada sampel',
                'jawaban_beneran' =>  'Terjadi Perubahan Warna Kuning Keruh',
                'pilihan_jawaban1' => 'Terjadi Warna Hijau Kekuningan',
                'pilihan_jawaban2' => 'Tidak Terjadi Perubahan Warna',
                'pilihan_jawaban3' => 'Tetap Bewarna Biru',

            ],
            [
                'id' => 57,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Aceton Apabila hasil dinyatakan positif ,maka pada sampel',
                'jawaban_beneran' => 'Terjadi Perubahan Warna Violet',
                'pilihan_jawaban1' => 'Terjadi Perubahan Warna Blue',
                'pilihan_jawaban2' => 'Terjadi Perubahan Warna Kuning',
                'pilihan_jawaban3' => 'Terjadi Perubahan Warna Hijau',

            ],
            [
                'id' => 58,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Bilirubin Regensia apakah yang digunakan',
                'jawaban_beneran' => 'Fauchet',
                'pilihan_jawaban1' => 'Benedict',
                'pilihan_jawaban2' => 'Amonia',
                'pilihan_jawaban3' => 'Asam Asetat 6%',

            ],
            [
                'id' => 59,
                'id_mapel' => 3,
                'soal' => 'Pada Pemeriksaan Sediment maka diperlukan…. Untuk melihat sediaan sediment',
                'jawaban_beneran' => 'Mikroskop',
                'pilihan_jawaban1' => 'Tabung',
                'pilihan_jawaban2' => 'Penjepit Tabung',
                'pilihan_jawaban3' => 'Glass Ukur',

            ],
            [
                'id' => 60,
                'id_mapel' => 3,
                'soal' => 'Pada Lensa Berapakah untuk melihat sediaan sediment',
                'jawaban_beneran' => '100 x',
                'pilihan_jawaban1' => '10 x',
                'pilihan_jawaban2' => '50 x',
                'pilihan_jawaban3' => '1000 x',

            ],
            [
                'id' => 61,
                'id_mapel' => 4,
                'soal' => 'Jenis Cacing tambang yang menyebabkan kelainan pada kulit adalah : ',
                'jawaban_beneran' => 'Ancylostoma duodenale',
                'pilihan_jawaban1' => 'Trichuris Trichura',
                'pilihan_jawaban2' => 'Necator Americanus',
                'pilihan_jawaban3' => 'Ancylostoma canium',

            ],
            [
                'id' => 62,
                'id_mapel' => 4,
                'soal' => 'Penyakit Trichinosis dapat didiagnosa dengan menemukan parasit di ',
                'jawaban_beneran' => 'Jaringan otot',
                'pilihan_jawaban1' => 'Mata',
                'pilihan_jawaban2' => 'Urine',
                'pilihan_jawaban3' => 'Cairan Empedu',

            ],
            [
                'id' => 63,
                'id_mapel' => 4,
                'soal' => 'Cacing yang mempunyai hospes defenitif dan hospes perantaranya sama adalah',
                'jawaban_beneran' => 'Trichinella Spiralis',
                'pilihan_jawaban1' => 'Enterobius Vermicularis',
                'pilihan_jawaban2' => 'Necator Americanus',
                'pilihan_jawaban3' => 'Hookworm',

            ],
            [
                'id' => 64,
                'id_mapel' => 4,
                'soal' => 'Infeksi cacing dibawah ini di diagnosanya yang menemukan bentuk cacing dewasa pada daerah luka ',
                'jawaban_beneran' =>  'Enterobius vermicularis',
                'pilihan_jawaban1' => '.Necator Americanus',
                'pilihan_jawaban2' => 'Trichinella Spiralis',
                'pilihan_jawaban3' => 'Hookworm',

            ],
            [
                'id' => 65,
                'id_mapel' => 4,
                'soal' => 'Jalur siklus hidup yang benar dari cacing tambang adalah ',
                'jawaban_beneran' => 'Telur-tanah-larva kulit-peredaran darah-jantung-paru – usus',
                'pilihan_jawaban1' => 'Telur – Kulit – Peredarah Darah – Jantung – Paru – Tenggorokan – Usus',
                'pilihan_jawaban2' => 'Larva – Tanah – Cacing Dewasa – Kulit – Peredarah Darah – Jantung – Paru – Usus',
                'pilihan_jawaban3' => 'Telur – Tanah – Mulut – Usus Halus – Hati – Jantung',

            ],
            [
                'id' => 66,
                'id_mapel' => 4,
                'soal' => 'Metode Harado Mori dipergunakan untuk diagnosa cacing ',
                'jawaban_beneran' => 'Tambang',
                'pilihan_jawaban1' => 'Pita',
                'pilihan_jawaban2' => 'Kremi',
                'pilihan_jawaban3' => 'Cambuk',

            ],
            [
                'id' => 67,
                'id_mapel' => 4,
                'soal' => 'Visera larva migrans disebabkan oleh ',
                'jawaban_beneran' => 'Toxocora Cati dan Toxocora Canis',
                'pilihan_jawaban1' => 'Necator Americanus',
                'pilihan_jawaban2' => 'Ancylostoma Duodenale',
                'pilihan_jawaban3' => 'Ancylostoma Duodenale dan Toxocora Cati',

            ],
            [
                'id' => 68,
                'id_mapel' => 4,
                'soal' => 'Gejala Anemia hipekrom mikrositer disebabkan oleh cacing',
                'jawaban_beneran' => 'Ancylostoma Duodenale',
                'pilihan_jawaban1' => 'Trichuris Spiralis',
                'pilihan_jawaban2' => 'Ancylostoma braziliense',
                'pilihan_jawaban3' => 'Toxocora Cati',

            ],
            [
                'id' => 69,
                'id_mapel' => 4,
                'soal' => 'Salah satu special dari Nematoda usus dibawah ini yang mempunyai 3(tiga) daur hidup adalah',
                'jawaban_beneran' => 'Strongyloides Stercoralis',
                'pilihan_jawaban1' => 'Trichuris Trichura',
                'pilihan_jawaban2' => 'Ascaris Lumbricoides',
                'pilihan_jawaban3' => 'Enterobius Vermicularis',

            ],
            [
                'id' => 70,
                'id_mapel' => 4,
                'soal' => 'Nematoda Usus tidak dapat menular dengan cara ',
                'jawaban_beneran' => 'Kontak Langsung Dengan Penderita',
                'pilihan_jawaban1' => 'Larva Menembus Kulit',
                'pilihan_jawaban2' => 'Tertelan Telur Emberio',
                'pilihan_jawaban3' => 'Melalui Vektor Biologis serangga',

            ],
            [
                'id' => 71,
                'id_mapel' => 4,
                'soal' => 'Bahan pemeriksaan untuk mendiagnosa Ancylostoma Duodenale adalah ',
                'jawaban_beneran' => 'Faeses',
                'pilihan_jawaban1' => 'Darah',
                'pilihan_jawaban2' => 'Sputum',
                'pilihan_jawaban3' => 'Nanah',

            ],
            [
                'id' => 72,
                'id_mapel' => 4,
                'soal' => 'Membedakan Ancylostoma Duodenale dengan Necator Americanus adalah',
                'jawaban_beneran' => 'Dari Cacing Dewasa dimana Ancylostoma Duodenale seperti huruf C sendangkan Necator Americanus seperti huruf S',
                'pilihan_jawaban1' => 'Dari Cacing Dewasa dimana Ancylostoma Duodenale seperti huruf S sendangkan Necator Americanus seperti huruf C',
                'pilihan_jawaban2' => 'Dari Telurnya dimana Ancylostoma Duodenale satu lapis sedangkan Necator Americanus Dua Lapis',
                'pilihan_jawaban3' => 'Dari Faeses nya dimana Ancylostoma Duodenale berbentuk cair sedangkan Necator Americanus bebentuk padat',

            ],
            [
                'id' => 73,
                'id_mapel' => 4,
                'soal' => 'Toxocora Cati adalah spesies dari kelas Nematoda, dimana bentuk telurnya menyerupai',
                'jawaban_beneran' =>  'Ascaris Lumbricoides',
                'pilihan_jawaban1' => 'T.Trichiura',
                'pilihan_jawaban2' => 'Hookworm',
                'pilihan_jawaban3' => 'Vermicularis',

            ],
            [
                'id' => 74,
                'id_mapel' => 4,
                'soal' => 'Trichinella Spiralis termasuk kedalam kelas',
                'jawaban_beneran' => 'Nematoda Usus',
                'pilihan_jawaban1' => 'Nematoda Jaringan',
                'pilihan_jawaban2' => 'Trematoda',
                'pilihan_jawaban3' => 'Cestoda',

            ],
            [
                'id' => 75,
                'id_mapel' => 4,
                'soal' => 'Untuk Mendiagnosa Toxocora Cati, bahan pemeriksaan yang diambil adalah',
                'jawaban_beneran' =>  'Faeses Kucing',
                'pilihan_jawaban1' => 'Nanah',
                'pilihan_jawaban2' => 'Faeses Manusia',
                'pilihan_jawaban3' => 'Faeses Babi',

            ],
            [
                'id' => 76,
                'id_mapel' => 4,
                'soal' => 'Untuk Mendiagnosa Ascaris Lumbricoides, bahan pemeriksaan yang diambil adalah',
                'jawaban_beneran' =>  'Faeses',
                'pilihan_jawaban1' => 'Sputum',
                'pilihan_jawaban2' => 'Darah',
                'pilihan_jawaban3' => 'Nanah',

            ],
            [
                'id' => 77,
                'id_mapel' => 4,
                'soal' => 'Nama lain dari Ascaris Lumbricoides adalah ',
                'jawaban_beneran' => 'Cacing Gelang',
                'pilihan_jawaban1' => 'Cacing Pita',
                'pilihan_jawaban2' => 'Cacing Tambang',
                'pilihan_jawaban3' => 'Cacing Tanah',

            ],
            [
                'id' => 78,
                'id_mapel' => 4,
                'soal' => 'Hospes dari Ascaris Lumbricoides adalah ',
                'jawaban_beneran' => 'Musca Domestika',
                'pilihan_jawaban1' => 'Apendix',
                'pilihan_jawaban2' => 'Colon Ascedens',
                'pilihan_jawaban3' => 'Colon Domestika',

            ],
            [
                'id' => 79,
                'id_mapel' => 4,
                'soal' => 'Cacing betina berukuran 10mm, mempunyai pelebaran kutikulum seperti sayap pada anterior, Ekor panjang runcing uterus melebar penuh dengan telur, ini identifikasi untuk cacing',
                'jawaban_beneran' =>  'Oxyuris Vermicularis',
                'pilihan_jawaban1' => 'Ancylostoma Duodenale',
                'pilihan_jawaban2' => 'Ascaris Lumbricoides',
                'pilihan_jawaban3' => 'Hookworm',

            ],
            [
                'id' => 80,
                'id_mapel' => 4,
                'soal' => 'Oxyuris vermicularis dapat terdiagnosa bila dalam bahan pemeriksaan ditemukan stadium ',
                'jawaban_beneran' =>  'Telur',
                'pilihan_jawaban1' => 'Telur dan Cacing',
                'pilihan_jawaban2' => 'Larra Filorium',
                'pilihan_jawaban3' => 'Larra Rabditiform',

            ],
            [
                'id' => 81,
                'id_mapel' => 5,
                'soal' => 'Reaksi Yang ditimbulkan tubuh akibat benda asing yang masuk dan merangsang sistem imun disebut : ',
                'jawaban_beneran' =>  'Respon Imunitas',
                'pilihan_jawaban1' => 'Respon Primer',
                'pilihan_jawaban2' => 'Respon Spesifik',
                'pilihan_jawaban3' => 'Respon Nonspesifik',

            ],
            [
                'id' => 82,
                'id_mapel' => 5,
                'soal' => 'Salah satu fungsi sistem imunitas adalah : ',
                'jawaban_beneran' =>  'Melindungi Tubuh',
                'pilihan_jawaban1' => 'Mengeluarkan Antigen',
                'pilihan_jawaban2' => 'Memproduksi Antibodi',
                'pilihan_jawaban3' => 'Membunuh Antigen',

            ],
            [
                'id' => 83,
                'id_mapel' => 5,
                'soal' => 'Sel hemopoetik yang terlibat dalam system imunitas adalah ',
                'jawaban_beneran' => 'Sel Plasma',
                'pilihan_jawaban1' => 'Eritrosit',
                'pilihan_jawaban2' => 'Makrofag',
                'pilihan_jawaban3' => 'Neutrofil',

            ],
            [
                'id' => 84,
                'id_mapel' => 5,
                'soal' => 'Kekebalan yang dimiliki pejamu terhadap efek buruk infeksi mikroba pathogen disebut',
                'jawaban_beneran' => 'Imunitas',
                'pilihan_jawaban1' => 'Imunologi',
                'pilihan_jawaban2' => 'Respon Imunologik',
                'pilihan_jawaban3' => 'Sistem Imunologik',

            ],
            [
                'id' => 85,
                'id_mapel' => 5,
                'soal' => 'yang berperan dalam pembentukan respon imunologi selular adalah ',
                'jawaban_beneran' =>  'Limfosit T',
                'pilihan_jawaban1' => 'Limfosit B',
                'pilihan_jawaban2' => 'Sel Plasma',
                'pilihan_jawaban3' => 'Antibodi',

            ],
            [
                'id' => 86,
                'id_mapel' => 5,
                'soal' => 'Imunitas yang terbentuk didalam tubuh walaupun sebelumnya tidak perna terpapar zat asing disebut ',
                'jawaban_beneran' => 'Respon Imun Spesifik',
                'pilihan_jawaban1' => 'Respon Imun Nonspesifik',
                'pilihan_jawaban2' => 'Respon Sekunder',
                'pilihan_jawaban3' => 'Respon Primer',

            ],
            [
                'id' => 87,
                'id_mapel' => 5,
                'soal' => 'Antigen yang terpapar untuk pertama kali disebut ',
                'jawaban_beneran' => 'Respon Primer',
                'pilihan_jawaban1' => 'Respon Sekunder',
                'pilihan_jawaban2' => 'Respon Selluer',
                'pilihan_jawaban3' => 'Respon Spesifik',

            ],
            [
                'id' => 88,
                'id_mapel' => 5,
                'soal' => 'Salah satu fase proses fagositosis adalah ',
                'jawaban_beneran' => 'Kemotaksis',
                'pilihan_jawaban1' => 'Toxicasi',
                'pilihan_jawaban2' => 'Survielance',
                'pilihan_jawaban3' => 'Fagositosis',

            ],
            [
                'id' => 89,
                'id_mapel' => 5,
                'soal' => 'Hal-hal dibawah ini berkaitan dengan dengan proses fagositosis kecuali ',
                'jawaban_beneran' => 'Limfosit T berperan dalam proses fagositosis',
                'pilihan_jawaban1' => 'Bersifat non spesifik seluller',
                'pilihan_jawaban2' => 'Merupakan proses memakan antigen',
                'pilihan_jawaban3' => 'Netrofil berperan proses fagositosis',
            ],
            [
                'id' => 90,
                'id_mapel' => 5,
                'soal' => 'Sel yang berperan pada proses non spesifik kecuali ',
                'jawaban_beneran' => 'Limfosit',
                'pilihan_jawaban1' => 'Monosit',
                'pilihan_jawaban2' => 'Makrofag',
                'pilihan_jawaban3' => 'Netrofil',
            ],
            [
                'id' => 91,
                'id_mapel' => 5,
                'soal' => 'Pengaturan respon imunitas dilakukan oleh ',
                'jawaban_beneran' => 'Limfosit T',
                'pilihan_jawaban1' => 'Antibodi',
                'pilihan_jawaban2' => 'Makrofag',
                'pilihan_jawaban3' => 'Sel Induk Limfoid',
            ],
            [
                'id' => 92,
                'id_mapel' => 5,
                'soal' => 'Antigen yang terpapar untuk kedua kali disebut ',
                'jawaban_beneran' => 'Respon Sekunder',
                'pilihan_jawaban1' => 'Respon Primer',
                'pilihan_jawaban2' => 'Respon Seluller',
                'pilihan_jawaban3' => 'Respon Spesifik',
            ],
            [
                'id' => 93,
                'id_mapel' => 5,
                'soal' => 'Sebagai Pendahulu makrofag adalah ',
                'jawaban_beneran' => 'Monosit',
                'pilihan_jawaban1' => 'Netrofil',
                'pilihan_jawaban2' => 'Eosinofil',
                'pilihan_jawaban3' => 'Limfosit',
            ],
            [
                'id' => 94,
                'id_mapel' => 5,
                'soal' => '.Mediator kimia yang dihasilkan oleh basofil adalah ',
                'jawaban_beneran' => 'Histamin',
                'pilihan_jawaban1' => 'Vaso Aktif Amine',
                'pilihan_jawaban2' => 'Monokin',
                'pilihan_jawaban3' => 'Limfokin',
            ],
            [
                'id' => 95,
                'id_mapel' => 5,
                'soal' => 'Pembentukan memory cell terjadi pada respon imun ',
                'jawaban_beneran' => 'Respon Imun Spesifik',
                'pilihan_jawaban1' => 'Respon Imun Seluller',
                'pilihan_jawaban2' => 'Respon Imun Nonspesifik',
                'pilihan_jawaban3' => 'Respon Imun Humoral',
            ],
            [
                'id' => 96,
                'id_mapel' => 5,
                'soal' => 'Sel dibawah ini disebut sebagai antigen presenting cell (APC) adalah',
                'jawaban_beneran' => 'Makrofag',
                'pilihan_jawaban1' => 'Sel Nk',
                'pilihan_jawaban2' => 'Eosinofil',
                'pilihan_jawaban3' => 'Basofil',
            ],
            [
                'id' => 97,
                'id_mapel' => 5,
                'soal' => 'Menghancurkan homestatis dari sistem imunitas tubuh adalah ',
                'jawaban_beneran' => 'Menghasilkan antigen yang masuk kedalam tubuh',
                'pilihan_jawaban1' => 'Menghancurkan sel-sel tumor',
                'pilihan_jawaban2' => 'Menghancurkan eritrosit yang tua',
                'pilihan_jawaban3' => 'Menghasilkan sel fagosit dan rusakan limfosit',
            ],
            [
                'id' => 98,
                'id_mapel' => 5,
                'soal' => 'Yang bukan sel fagosit',
                'jawaban_beneran' =>  'Basofil',
                'pilihan_jawaban1' => 'Monosit',
                'pilihan_jawaban2' => 'Netrofil',
                'pilihan_jawaban3' => 'Makrofag',
            ],
            [
                'id' => 99,
                'id_mapel' => 5,
                'soal' => 'Fungsi factor kemotaktik adalah ',
                'jawaban_beneran' => 'Menarik sel fagosit ketempat Infeksi',
                'pilihan_jawaban1' => 'Memudahkan sel asing untuk difagosit',
                'pilihan_jawaban2' => 'Melindungi tubuh terhadap infeksi virus',
                'pilihan_jawaban3' => 'Memudahkan antigen untuk dimusnahkan',
            ],
            [
                'id' => 100,
                'id_mapel' => 5,
                'soal' => 'Imunitas non spesifik melindungi tubuh dengan cara ',
                'jawaban_beneran' =>  'Reaksi Inflamasi',
                'pilihan_jawaban1' => 'Fagosit',
                'pilihan_jawaban2' => 'Pembentukan Antibody',
                'pilihan_jawaban3' => 'Menghasilkan Interferon',
            ],
            [
                'id' => 101,
                'id_mapel' => 6,
                'soal' => 'Untuk Memeriksa Kehamilan Wanita maka diperlukan pemeriksaan',
                'jawaban_beneran' => 'HCG',
                'pilihan_jawaban1' => 'BBC',
                'pilihan_jawaban2' => 'HGB',
                'pilihan_jawaban3' => 'GCH',
            ],
            [
                'id' => 102,
                'id_mapel' => 6,
                'soal' => 'HCG Merupakan Singkatan Dari',
                'jawaban_beneran' => 'Human Chrionic Gonadotropin',
                'pilihan_jawaban1' => 'Human Calsium Gowaslu',
                'pilihan_jawaban2' => 'How Chrionic Gopastu',
                'pilihan_jawaban3' => 'Human Calsium Gonadotropin',
            ],
            [
                'id' => 103,
                'id_mapel' => 6,
                'soal' => 'Treponema Pallidum adalah penyebab penyakit',
                'jawaban_beneran' => 'Sifilis',
                'pilihan_jawaban1' => 'Diabetes',
                'pilihan_jawaban2' => 'Kanker',
                'pilihan_jawaban3' => 'Ebola',
            ],
            [
                'id' => 104,
                'id_mapel' => 6,
                'soal' => 'Pada Pemeriksaan ASTO berpakah nilai normal nya',
                'jawaban_beneran' =>  'Dibawah 160 todd/unit',
                'pilihan_jawaban1' => '160-200 todd/unit',
                'pilihan_jawaban2' => '200-300 todd/unit',
                'pilihan_jawaban3' => '160 tood/unit',
            ],
            [
                'id' => 105,
                'id_mapel' => 6,
                'soal' => 'Dibawah ini faktor resiko Rheumatoid Arthritis kecuali',
                'jawaban_beneran' => 'Tidur yang cukup',
                'pilihan_jawaban1' => 'Gaya Hidup',
                'pilihan_jawaban2' => 'Merokok',
                'pilihan_jawaban3' => 'Pekerjaan',
            ],
            [
                'id' => 106,
                'id_mapel' => 6,
                'soal' => 'Salmonella typi memiliki 3antigen kecuali ',
                'jawaban_beneran' => 'Antigen A',
                'pilihan_jawaban1' => 'Antigen O',
                'pilihan_jawaban2' => 'Antigen H',
                'pilihan_jawaban3' => 'Antigen Vi',
            ],
            [
                'id' => 107,
                'id_mapel' => 6,
                'soal' => 'Tujuan Dari Tes Widal adalah',
                'jawaban_beneran' => 'Untuk mendeteksi adanya antibodi terhadap antigen Salmonella Typhi',
                'pilihan_jawaban1' => 'Untuk mendeteksi adanya Bakteri Salmonella Typhi',
                'pilihan_jawaban2' => 'Untuk Mendeteksi adanya Reaksi Aglutinasi',
                'pilihan_jawaban3' => 'Untuk Mendekteksi kuman streptoccocus',
            ],
            [
                'id' => 108,
                'id_mapel' => 6,
                'soal' => 'Uji Tubex adalah',
                'jawaban_beneran' => 'Pengujian adanya Antibodi IgM',
                'pilihan_jawaban1' => 'Pengujian adanya Antibodi IgA',
                'pilihan_jawaban2' => 'Pengujian adanya Antibodi IgN',
                'pilihan_jawaban3' => 'Pengujian adanya Antibodi IgK',
            ],
            [
                'id' => 109,
                'id_mapel' => 6,
                'soal' => 'Dibawah ini faktor risiko yang tidak dapat di modifikasi dari Rheumatik Arthristis, Kecuali',
                'jawaban_beneran' =>  'Olahraga',
                'pilihan_jawaban1' => 'Faktor Genetik',
                'pilihan_jawaban2' => 'Usia',
                'pilihan_jawaban3' => 'Jenis Kelamin',
            ],
            [
                'id' => 110,
                'id_mapel' => 6,
                'soal' => 'Bahan Pemeriksaan Untuk Widal Adalah',
                'jawaban_beneran' =>  'Serum',
                'pilihan_jawaban1' => 'Darah',
                'pilihan_jawaban2' => 'Sputum',
                'pilihan_jawaban3' => 'Faeses',
            ],
            [
                'id' => 111,
                'id_mapel' => 6,
                'soal' => 'Penularan Sifilis Dari',
                'jawaban_beneran' =>  'Hubungan Kontak Seksual',
                'pilihan_jawaban1' => 'Berjabat Tangan',
                'pilihan_jawaban2' => 'Makanan',
                'pilihan_jawaban3' => 'Kotoran',
            ],
            [
                'id' => 112,
                'id_mapel' => 6,
                'soal' => 'Metode Pemeriksaan ASTO adalah',
                'jawaban_beneran' => 'Ortho Anti Streptolysin O',
                'pilihan_jawaban1' => 'Ortho Anti Staphylococcus O',
                'pilihan_jawaban2' => 'Ortho Anti Sreptoccous O',
                'pilihan_jawaban3' => 'Orto Anto Sifil O',
            ],
            [
                'id' => 113,
                'id_mapel' => 6,
                'soal' => 'Regensia Yang digunakan Untuk Pemeriksaan Golongan Darah adalah',
                'jawaban_beneran' => 'Anti Sera A dan Anti Sera B',
                'pilihan_jawaban1' => 'Anti Sera A',
                'pilihan_jawaban2' => 'Anti Sera B',
                'pilihan_jawaban3' => 'Anti Sera C dan Anti Sera D',
            ],
            [
                'id' => 114,
                'id_mapel' => 6,
                'soal' => 'Apabila Pada Sampel yang tercampur antisera A membentuk aglutinasi,maka hasil yang disimpulkan',
                'jawaban_beneran' => 'Golongan Darah A',
                'pilihan_jawaban1' => 'Golongan Darah B',
                'pilihan_jawaban2' => 'Golongan Darah O',
                'pilihan_jawaban3' => 'Golongan Darah AB',
            ],
            [
                'id' => 115,
                'id_mapel' => 6,
                'soal' => 'Prinsip dari Pemeriksaan VDRL adalah',
                'jawaban_beneran' => 'Antibodi dalam serum yang dicampur dengan reagensia latex syphfikal akan membentuk Flokulasi',
                'pilihan_jawaban1' => 'Antibodi dalam serum yang dicampur dengan reagensia latex syphfikal akan membentuk Aglutinasi',
                'pilihan_jawaban2' => 'Antibodi dalam serum yang dicampur dengan reagensia latex syphilosal akan membentuk Flokulasi',
                'pilihan_jawaban3' => 'Antibodi dalam serum yang dicampur dengan reagensia latex syphfikal akan membentuk Koagulasi',
            ],
            [
                'id' => 116,
                'id_mapel' => 6,
                'soal' => 'Apa Tujuan dari Pemeriksaan CRP',
                'jawaban_beneran' => 'Untuk Mendeteksi adanya C- Reaktive protein dalam Serum',
                'pilihan_jawaban1' => 'Untuk Mendeteksi adanya C+ Reaktive protein dalam Serum',
                'pilihan_jawaban2' => 'Untuk Mendeteksi adanya C- Reaktive protein dalam Darah',
                'pilihan_jawaban3' => 'Untuk Mendeteksi adanya C+ Reaktive protein dalam Darah',
            ],
                        [
                'id' =>117,
                'id_mapel' => 6,
                'soal' => 'Regensia apa yang digunakan pada Pemeriksaan CRP',
                'jawaban_beneran' =>  'Latex CRP',
                'pilihan_jawaban1' => 'Latex ASTO',
                'pilihan_jawaban2' => 'Komus CRP',
                'pilihan_jawaban3' => 'Ratex CRP',
            ],
            [
                'id' => 118,
                'id_mapel' => 6,
                'soal' => 'Pada Pemeriksaan HBsAg, metode apakah yang digunakan',
                'jawaban_beneran' => 'Imunocromatografi',
                'pilihan_jawaban1' => 'Imunitas',
                'pilihan_jawaban2' => 'Imunologi',
                'pilihan_jawaban3' => 'Imunocrokaligrafi',
            ],
            [
                'id' => 119,
                'id_mapel' => 6,
                'soal' => 'Munculnya ruam di kulit atau luka seperti sariawan di mulut, vagina dan usus. Ruam yang ditimbulkan yakni kasar, merah atau bintik coklat kemerahan yang terdapat di telapak kaki maupun telapak tangan, terkadang ruamnya terjadi di bagian tubuh lainnya, pada pernyataan tersebut maka sifilis sudah masuk pada fase ?',
                'jawaban_beneran' => 'Fase Sekunder',
                'pilihan_jawaban1' => 'Fase Laten',
                'pilihan_jawaban2' => 'Fase Primer',
                'pilihan_jawaban3' => 'Fase Latex',
            ],
            [
                'id' => 120,
                'id_mapel' => 6,
                'soal' => 'Munculnya luka sifilis (chancre) tunggal atau lebih dari satu. Bentuknya seperti sariawan, bulat, dan tidak terasa nyeri. Lokasi luka sifilis merupakan pertanda tempat masuknya infeksi sifilis ke dalam tubuh yang berkembang di lokasi tempat masuknya bakteri T.Pallidum, beberapa diantaranya menyebar ke kelenjar limfe dan menuju aliran darah, pada pernyataan tersebut maka sifilis sudah masuk pada fase ?',
                'jawaban_beneran' =>  'Fase Primer',
                'pilihan_jawaban1' => 'Fase Laten',
                'pilihan_jawaban2' => 'Fase Sekunder',
                'pilihan_jawaban3' => 'Fase Latex',
            ],
            [
                'id' => 121,
                'id_mapel' => 7,
                'soal' => 'Berikut ini Faktor analisa Makanan Kecuali',
                'jawaban_beneran' => 'Agar bisa makan lebih banyak',
                'pilihan_jawaban1' => 'Kontrol kualitas dalam memproduksi makanan',
                'pilihan_jawaban2' => 'Keinginan untuk memperoleh pengetahuan dalam hal gizi dan kimia hayat, yang perlu untuk mencapai keadaan makhluk hidup yang sehat melalui makanan',
                'pilihan_jawaban3' => 'Kebutuhan untuk menyusun peraturan tentang pajak makanan dan minuman',
            ],
            [
                'id' => 122,
                'id_mapel' => 7,
                'soal' => 'Apakah Tujuan dari Analisa Makanan ',
                'jawaban_beneran' => 'Untuk mengetahui susunan kimia dari makanan dan dengan pengetahuan dalam hal gizi dan kimia hayar',
                'pilihan_jawaban1' => 'Agar bisa makan lebih banyak',
                'pilihan_jawaban2' => 'Untuk mengetahui Kelezatan makanan',
                'pilihan_jawaban3' => 'Agar mengetahui harga jual makanan',
            ],
            [
                'id' => 123,
                'id_mapel' => 7,
                'soal' => 'Analisa Makanan adalah Cabang dari ilmu',
                'jawaban_beneran' => 'Kimia Analitika',
                'pilihan_jawaban1' => 'Biokimia',
                'pilihan_jawaban2' => 'Fisika',
                'pilihan_jawaban3' => 'Hematologi',
            ],
            [
                'id' => 124,
                'id_mapel' => 7,
                'soal' => 'Dibawah ini adalah syarat-syarat dari wadah,kecuali',
                'jawaban_beneran' => 'Tidak Menjaga Keutuhan dan keaslian isinya',
                'pilihan_jawaban1' => 'Tidak terpengaruh oleh isi',
                'pilihan_jawaban2' => 'Tidak boleh merugikan atau membahayakan konsumen',
                'pilihan_jawaban3' => 'Tahan terhadap perlakuan selama pengolahan',
            ],
            [
                'id' => 125,
                'id_mapel' => 7,
                'soal' => 'Fungsi Label pada kemasan makanan adalah',
                'jawaban_beneran' => 'Untuk memberikan keterangan Nama,Merk,Komposisi,Netto, alamat dan Kode Produksi',
                'pilihan_jawaban1' => 'Untuk memberikan Keterangan Nama,Merk.dan Harga Jual',
                'pilihan_jawaban2' => 'Untuk memberikan Keterangan Netto,alamat dan Kode Produksi',
                'pilihan_jawaban3' => 'Untuk memberikan Keterangan Halal atau tidaknya',
            ],
            [
                'id' => 126,
                'id_mapel' => 7,
                'soal' => 'Yang tidak termasuk komposisi Karbohidrat adalah',
                'jawaban_beneran' => 'Telur',
                'pilihan_jawaban1' => 'Beras',
                'pilihan_jawaban2' => 'Jagung',
                'pilihan_jawaban3' => 'Karbohidrat',
            ],
            [
                'id' => 127,
                'id_mapel' => 7,
                'soal' => 'Pada Pemeriksaan Karbohidrat manakah Sampel pada Makanan ',
                'jawaban_beneran' => 'Tepung,Mie Instan',
                'pilihan_jawaban1' => 'Gula',
                'pilihan_jawaban2' => 'Sirup,Madu',
                'pilihan_jawaban3' => 'Air Tebu',
            ],
            [
                'id' => 128,
                'id_mapel' => 7,
                'soal' => 'Prosedur Penetapan Kadar etanol dapat dilakukan dengan cara berikut kecuali',
                'jawaban_beneran' => 'Penetapan Kadar Karbohidrat',
                'pilihan_jawaban1' => 'Ekstrasi',
                'pilihan_jawaban2' => 'Penetapan Bobot Jenis',
                'pilihan_jawaban3' => 'Penetapan Kadar Alkohol',
            ],
            [
                'id' => 129,
                'id_mapel' => 7,
                'soal' => 'Fungsi Karbohidrat adalah',
                'jawaban_beneran' => 'Menyediakan energi untuk proses -proses yang terjadi didalam tubuh.',
                'pilihan_jawaban1' => 'Menyediakan energi untuk proses belajar',
                'pilihan_jawaban2' => 'menyediakan energi untuk kekebalan tubuh',
                'pilihan_jawaban3' => 'Menyediakan energi untuk menambahkan darah',
            ],
            [
                'id' => 130,
                'id_mapel' => 7,
                'soal' => 'Lemak dan Minyak termasuk ke dalam kelompok senyawa',
                'jawaban_beneran' => 'Lipida',
                'pilihan_jawaban1' => 'Lipoid',
                'pilihan_jawaban2' => 'Antron',
                'pilihan_jawaban3' => 'Trigliserida',
            ],
            [
                'id' => 131,
                'id_mapel' => 7,
                'soal' => 'Berikut adalah Analisa Kualitatif pada makanan Kecuali,',
                'jawaban_beneran' => 'Uji Fuchsin',
                'pilihan_jawaban1' => 'Uji Molish',
                'pilihan_jawaban2' => 'Uji Antron',
                'pilihan_jawaban3' => 'Uji Barfoet',
            ],
            [
                'id' => 132,
                'id_mapel' => 7,
                'soal' => 'Berikut Penyebab kerusakan lemak kecuali',
                'jawaban_beneran' => 'Reaksi Sekunder',
                'pilihan_jawaban1' => 'Reaksi Oksidasi',
                'pilihan_jawaban2' => 'Hidrolisa',
                'pilihan_jawaban3' => 'Penyerapan Bau',
            ],
            [
                'id' => 133,
                'id_mapel' => 7,
                'soal' => 'Apabila ditemukan Karbohidarat pada bahan pada Uji Molish Maka',
                'jawaban_beneran' => 'Kedua cairan terbentuk cincin bewarna violet pada batas kedua cairan',
                'pilihan_jawaban1' => 'kedua cairan terbentuk endapan violet',
                'pilihan_jawaban2' => 'tidak terjadi perubahan',
                'pilihan_jawaban3' => 'kedua cairan terbentuk cincin bewarna merah pada batas kedua cairan',
            ],
            [
                'id' => 134,
                'id_mapel' => 7,
                'soal' => 'Apabila ditemukan Monosakarida pada bahan pada Uji Barfoed Maka ',
                'jawaban_beneran' => 'Terbentuknya warna merah bata',
                'pilihan_jawaban1' => 'Terbentuknya warna merah ',
                'pilihan_jawaban2' => 'Terbentuknya warna merah muda',
                'pilihan_jawaban3' => 'Terbentuknya warna kuning',
            ],
            [
                'id' => 135,
                'id_mapel' => 7,
                'soal' => 'Pada uji coba Iodium terbentuknya warna Biru hasil yang didapat adalah',
                'jawaban_beneran' => 'Adanya Amilum pada Bahan',
                'pilihan_jawaban1' => 'Adanya Dekstrin pada bahan',
                'pilihan_jawaban2' => 'Adanya Monosakarida pada bahan',
                'pilihan_jawaban3' => 'Adanya Fruktosa pada bahan',
            ],
            [
                'id' => 136,
                'id_mapel' => 7,
                'soal' => 'Pada uji coba Iodium terbentuknya warna Merah hasil yang didapat adalah',
                'jawaban_beneran' => 'Adanya Dekstrin pada bahan',
                'pilihan_jawaban1' => 'Adanya Amilum pada bahan',
                'pilihan_jawaban2' => 'Adanya Monosakarida pada bahan',
                'pilihan_jawaban3' => 'Adanya Fruktosa pada bahan',
            ],
            [
                'id' => 137,
                'id_mapel' => 7,
                'soal' => 'Berikut adalah Regensia yang digunakan pada Pemeriksaan Kadar Natrium Klorida,Kecuali',
                'jawaban_beneran' => 'Benedict',
                'pilihan_jawaban1' => 'Natrium Klorida',
                'pilihan_jawaban2' => 'Kalium Kromat 5%',
                'pilihan_jawaban3' => 'Perak Nitrat 0,01N',
            ],
            [
                'id' => 138,
                'id_mapel' => 7,
                'soal' => 'Untuk standarisasi Kadar Natrium,berapa Natrium Klorida yang perlu ditimbang',
                'jawaban_beneran' => '0,5850 Gram',
                'pilihan_jawaban1' => '5850 Gram',
                'pilihan_jawaban2' => '0.5900 Gram',
                'pilihan_jawaban3' => '5900 Gram',
            ],
            [
                'id' => 139,
                'id_mapel' => 7,
                'soal' => 'Tujuan dari Pemeriksaan Bilangan Asam Adalah',
                'jawaban_beneran' => 'Melakukan pemeriksaan Asam pada lemak dan minyak',
                'pilihan_jawaban1' => 'Melakukan Pemeriksaan Basa pada lemak dan minyak',
                'pilihan_jawaban2' => 'Melakukan Pemeriksaan Kadar Lemak dan Minyak',
                'pilihan_jawaban3' => 'Melakukan Pemeriksaan Nilai Normal',
            ],
            [
                'id' => 140,
                'id_mapel' => 7,
                'soal' => 'Pada Pemeriksaan Bilangan Asam, Berapa gram sampel minyak yang harus di timbang',
                'jawaban_beneran' => '10 Gram',
                'pilihan_jawaban1' => '100 Gram',
                'pilihan_jawaban2' => '50 Gram',
                'pilihan_jawaban3' => '20 Gram',
            ],
            [
                'id' => 141,
                'id_mapel' => 8,
                'soal' => 'Penetapan Klorida dapat dilakukan dengan methoda berikut,kecuali',
                'jawaban_beneran' => 'Nessler',
                'pilihan_jawaban1' => 'Fayan',
                'pilihan_jawaban2' => 'Mhor',
                'pilihan_jawaban3' => 'Folhard',
            ],
            [
                'id' => 142,
                'id_mapel' => 8,
                'soal' => 'pH contoh air yang diolah untuk analisa Khlorida methoda Mhor adalah',
                'jawaban_beneran' => 'Netral sedikit alkalis',
                'pilihan_jawaban1' => 'Netral',
                'pilihan_jawaban2' => 'Asam',
                'pilihan_jawaban3' => 'Basa',
            ],
            [
                'id' => 143,
                'id_mapel' => 8,
                'soal' => 'Pada akhir titrasi analisa khlorida methoda Mhor,akan terbentuk endapan Ag2CrO4 yang bewarna',
                'jawaban_beneran' => 'Kuning Merah',
                'pilihan_jawaban1' => 'Kuning',
                'pilihan_jawaban2' => 'Biru',
                'pilihan_jawaban3' => 'Jingga',
            ],
            [
                'id' => 144,
                'id_mapel' => 8,
                'soal' => 'Indikator K2Cr pada analisa khlorida methoda Mhor akan berubah menjadi Cr2O7 pada pH',
                'jawaban_beneran' => '7',
                'pilihan_jawaban1' => '6',
                'pilihan_jawaban2' => '9',
                'pilihan_jawaban3' => '12',
            ],
            [
                'id' => 145,
                'id_mapel' => 8,
                'soal' => 'Peganggu pada analisa khlorida metoda mhor adalah senyawa berikut, kecuali',
                'jawaban_beneran' => 'Cyanida',
                'pilihan_jawaban1' => 'Sulfit',
                'pilihan_jawaban2' => 'Fosfat',
                'pilihan_jawaban3' => 'Sulfat',
            ],
            [
                'id' => 146,
                'id_mapel' => 8,
                'soal' => 'Senyawa yang dapat menyebabkan konsumsi sabun menjadi lebih tinggi ialah',
                'jawaban_beneran' => 'Kalsium',
                'pilihan_jawaban1' => 'Kalium',
                'pilihan_jawaban2' => 'Arsen',
                'pilihan_jawaban3' => 'Khlorida',
            ],
            [
                'id' => 147,
                'id_mapel' => 8,
                'soal' => 'Senyawa yang dapat menyebabkan kesadahan sementara',
                'jawaban_beneran' => 'MgHCO3',
                'pilihan_jawaban1' => 'CaSO4',
                'pilihan_jawaban2' => 'MgCi2',
                'pilihan_jawaban3' => 'MgSO3',
            ],
            [
                'id' => 148,
                'id_mapel' => 8,
                'soal' => 'Kesadahan Sementara dapat dihilangkan dengan cara',
                'jawaban_beneran' => 'Mendidihkan Sampel',
                'pilihan_jawaban1' => 'Mengendapan Sampel',
                'pilihan_jawaban2' => 'Menambahkan Asam',
                'pilihan_jawaban3' => 'Menyaring Sampel',
            ],
            [
                'id' => 149,
                'id_mapel' => 8,
                'soal' => 'Methoda analisa kesadahan adalah sebagai berikut kecuali',
                'jawaban_beneran' => 'Netralisasi',
                'pilihan_jawaban1' => 'Gravimetri',
                'pilihan_jawaban2' => 'Kompleksometri',
                'pilihan_jawaban3' => 'Permanganometri',
            ],
            [
                'id' => 150,
                'id_mapel' => 8,
                'soal' => 'Analisa Kesadahan methoda kompleksomteri menggunakan larutan standar sekunder',
                'jawaban_beneran' => 'EDTA',
                'pilihan_jawaban1' => 'CaCO3',
                'pilihan_jawaban2' => 'KmnO4',
                'pilihan_jawaban3' => 'AgNO3',
            ],
            [
                'id' => 151,
                'id_mapel' => 8,
                'soal' => 'Senyawa EDTA yang dijual dalam bentuk garam natrium dengan nama Compelsomteri III berasal dari',
                'jawaban_beneran' => 'USA',
                'pilihan_jawaban1' => 'Swiss',
                'pilihan_jawaban2' => 'Jerman',
                'pilihan_jawaban3' => 'Rusia',
            ],
            [
                'id' => 152,
                'id_mapel' => 8,
                'soal' => 'Bila EDTA ditambahkan pada suatu larutan yang mengandung ion Ca & Mg pada pH 10+0,1 maka larutan akan bewarna',
                'jawaban_beneran' => 'Merah Anggur',
                'pilihan_jawaban1' => 'Biru',
                'pilihan_jawaban2' => 'Violet',
                'pilihan_jawaban3' => 'Kuning Merah',
            ],
            [
                'id' => 153,
                'id_mapel' => 8,
                'soal' => 'Indikator yang digunakan pada analisa kesadahan Kalsium methoda Kompleksometri adalah ',
                'jawaban_beneran' => 'Mureksid',
                'pilihan_jawaban1' => 'EBT ',
                'pilihan_jawaban2' => 'Methil Red ',
                'pilihan_jawaban3' => 'Phenolphtalein',
            ],
            [
                'id' => 154,
                'id_mapel' => 8,
                'soal' => 'Pada Akhir Titrasi analisa kesadahan Kalsium akan terbentuk warna',
                'jawaban_beneran' => 'Violet',
                'pilihan_jawaban1' => 'Biru',
                'pilihan_jawaban2' => 'Merah',
                'pilihan_jawaban3' => 'Kuning',
            ],
            [
                'id' => 155,
                'id_mapel' => 8,
                'soal' => 'Untuk mendapatkan gamabran adanya pengotor didalam air yang disebabkan oleh manusia atau binatang, maka dilakukan analisa ',
                'jawaban_beneran' => 'Zat Organik',
                'pilihan_jawaban1' => 'Khlorida',
                'pilihan_jawaban2' => 'Kesadahan',
                'pilihan_jawaban3' => 'Alkalinitas',
            ],
            [
                'id' => 156,
                'id_mapel' => 8,
                'soal' => 'Penetapan kadar zat oraganik dapat dilakukan dengan cara ',
                'jawaban_beneran' => 'Mhor',
                'pilihan_jawaban1' => 'Winkler',
                'pilihan_jawaban2' => 'Kubel Tieman',
                'pilihan_jawaban3' => 'Nessler',
            ],
            [
                'id' => 157,
                'id_mapel' => 8,
                'soal' => 'Senyawa yang tidak dapat dioksidasi oleh KmnO4 adalah',
                'jawaban_beneran' => 'Detergen',
                'pilihan_jawaban1' => 'Protein',
                'pilihan_jawaban2' => 'Phenol',
                'pilihan_jawaban3' => 'Kharbohidrat',
            ],
            [
                'id' => 158,
                'id_mapel' => 8,
                'soal' => 'Senyawa Berikut yang menggangu pada analisa zat organik, kecuali',
                'jawaban_beneran' => 'H2S',
                'pilihan_jawaban1' => 'Sulfida',
                'pilihan_jawaban2' => 'Sulfat',
                'pilihan_jawaban3' => 'Nitrit',
            ],
            [
                'id' => 159,
                'id_mapel' => 8,
                'soal' => 'Ion penyebab alkalinitas, kecuali',
                'jawaban_beneran' => 'Borat ',
                'pilihan_jawaban1' => 'Karbonat',
                'pilihan_jawaban2' => 'Sulfat ',
                'pilihan_jawaban3' => 'Bikarbonat',
            ],
            [
                'id' => 160,
                'id_mapel' => 8,
                'soal' => 'Untuk analisa alkalinitas dapat menggunakan methoda',
                'jawaban_beneran' => 'Permangonometri',
                'pilihan_jawaban1' => 'Kompleksometri',
                'pilihan_jawaban2' => 'Potensiometeri',
                'pilihan_jawaban3' => 'Iodometri',
            ],
        ];
        DB::table('dedi_latihan')->insert($defaulData);
    }



    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('dedi_latihan');
    }
}

