<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateGedmiMapelTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('gedmi_mapel', function (Blueprint $table) {
            $table->id();
            $table->string('hari');
            $table->string('jam');
            $table->string('nama_guru');
            $table->string('bidang_studi');
            $table->string('kelas');
            $table->timestamps();
        });

        $defaultData = [
            [
                'id' => 1,
                'hari' => 'Senin',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'hari' => 'Senin',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris	',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'hari' => 'Senin',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA	',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'hari' => 'Senin',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'hari' => 'Senin',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'hari' => 'Senin',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'hari' => 'Senin',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Novenna Nurmalasari, S.Kom',
                'bidang_studi' => 'Prakarya',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'hari' => 'Senin',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Novenna Nurmalasari, S.Kom',
                'bidang_studi' => 'Prakarya',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'hari' => 'Senin',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Dr. Mesran, M.Pdi',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'hari' => 'Senin',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Dr. Mesran, M.Pdi',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'hari' => 'Senin',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'hari' => 'Senin',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'hari' => 'Senin',
                'jam' => '10.45 - 11.15',
                'nama_guru' => 'Almas Adlina,S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'hari' => 'Senin',
                'jam' => '11.15 - 11.45',
                'nama_guru' => 'Agung Sihotang, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'hari' => 'Senin',
                'jam' => '11.45 - 12.15',
                'nama_guru' => 'Agung Sihotang, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'hari' => 'Senin',
                'jam' => '12.15 - 12.45',
                'nama_guru' => 'Agung Sihotang, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'hari' => 'Senin',
                'jam' => '12.45 - 13.15',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           
            [
                'id' => 18,
                'hari' => 'Senin',
                'jam' => '13.15 - 13.45',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'hari' => 'Selasa',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'hari' => 'Selasa',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'hari' => 'Selasa',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'hari' => 'Selasa',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'hari' => 'Selasa',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'hari' => 'Selasa',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'hari' => 'Selasa',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'hari' => 'Selasa',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'PKN',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'hari' => 'Selasa',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika	',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'hari' => 'Selasa',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika	',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'hari' => 'Selasa',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'hari' => 'Selasa',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'hari' => 'Selasa',
                'jam' => '10.45 - 11.15',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'IPS',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'hari' => 'Selasa',
                'jam' => '11.15 - 11.45',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'IPS',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'hari' => 'Selasa',
                'jam' => '11.45 - 12.15',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'hari' => 'Selasa',
                'jam' => '12.15 - 12.45',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'hari' => 'Selasa',
                'jam' => '12.45 - 13.15',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'hari' => 'Selasa',
                'jam' => '13.15 - 13.45',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'hari' => 'Rabu',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'hari' => 'Rabu',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'ZL. Purba, A.Md',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'hari' => 'Rabu',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'hari' => 'Rabu',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'hari' => 'Rabu',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'hari' => 'Rabu',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'hari' => 'Rabu',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'hari' => 'Rabu',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'hari' => 'Rabu',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Dr. Mesran, M.Pdi',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'hari' => 'Rabu',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'hari' => 'Rabu',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'hari' => 'Rabu',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'hari' => 'Rabu',
                'jam' => '10.45 - 11.15',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'hari' => 'Rabu',
                'jam' => '11.15 - 11.45',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'hari' => 'Rabu',
                'jam' => '11.45 - 12.15',
                'nama_guru' => 'Almas Adlina,S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'hari' => 'Rabu',
                'jam' => '12.15 - 12.45',
                'nama_guru' => 'Almas Adlina,S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'hari' => 'Rabu',
                'jam' => '12.45 - 13.15',
                'nama_guru' => 'Almas Adlina,S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'hari' => 'Rabu',
                'jam' => '13.15 - 13.45',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'Bahasa Inggris',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'hari' => 'Kamis',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'hari' => 'Kamis',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'hari' => 'Kamis',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Jessica Yolanda, S.Pd',
                'bidang_studi' => 'SBK',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'hari' => 'Kamis',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'IPS',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'hari' => 'Kamis',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'hari' => 'Kamis',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'hari' => 'Kamis',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'hari' => 'Kamis',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Siti Agustina Julita, S.Pd',
                'bidang_studi' => 'Matematika	',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'hari' => 'Kamis',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'hari' => 'Kamis',
                'jam' => '09.00 - 09.30',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'hari' => 'Kamis',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'hari' => 'Kamis',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Intan Sari Siregar, S.Pd',
                'bidang_studi' => 'IPA',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'hari' => 'Kamis',
                'jam' => '10.45 - 11.15',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'hari' => 'Kamis',
                'jam' => '11.15 - 11.45',
                'nama_guru' => 'Diana Susanti, Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'hari' => 'Kamis',
                'jam' => '11.45 - 12.15',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'hari' => 'Kamis',
                'jam' => '12.15 - 12.45',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'hari' => 'Kamis',
                'jam' => '12.45 - 13.15',
                'nama_guru' => 'Novenna Nurmalasari, S.Kom',
                'bidang_studi' => 'Prakarya',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'hari' => 'Kamis',
                'jam' => '13.15 - 13.45',
                'nama_guru' => 'Novenna Nurmalasari, S.Kom',
                'bidang_studi' => 'Prakarya',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'hari' => 'Jumat',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'hari' => 'Jumat',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Hengki S. Sianturi, S.Pd',
                'bidang_studi' => 'Penjas',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'hari' => 'Jumat',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama	',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'hari' => 'Jumat',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama	',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'hari' => 'Jumat',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama	',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'hari' => 'Jumat',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'hari' => 'Jumat',
                'jam' => '09.15 - 09.45',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'hari' => 'Jumat',
                'jam' => '09.45 - 10.15',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'hari' => 'Jumat',
                'jam' => '10.15 - 10.40',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'hari' => 'Sabtu',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Pramuka',
                'bidang_studi' => 'Salamuddin',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'hari' => 'Sabtu',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Pramuka',
                'bidang_studi' => 'Salamuddin',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'hari' => 'Sabtu',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama	',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'hari' => 'Sabtu',
                'jam' => '09.30 - 10.00',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama	',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'hari' => 'Sabtu',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'hari' => 'Sabtu',
                'jam' => '07.30 - 08.00',
                'nama_guru' => 'Pramuka',
                'bidang_studi' => 'Salamuddin',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'hari' => 'Sabtu',
                'jam' => '08.00 - 08.30',
                'nama_guru' => 'Pramuka',
                'bidang_studi' => 'Salamuddin',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'hari' => 'Sabtu',
                'jam' => '08.30 - 09.00',
                'nama_guru' => 'Diana Susanti Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'hari' => 'Sabtu',
                'jam' => '09.35 - 10.00',
                'nama_guru' => 'Diana Susanti Siregar, S.Pd',
                'bidang_studi' => 'B.Indonesia',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'hari' => 'Sabtu',
                'jam' => '10.00 - 10.30',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'hari' => 'Sabtu',
                'jam' => '10.15 - 10.45',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'hari' => 'Sabtu',
                'jam' => '10.45 - 11.15',
                'nama_guru' => 'Gaya Baiduri, S.Pdi',
                'bidang_studi' => 'Agama',
                'Kelas' => 'IX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'hari' => 'Sabtu',
                'jam' => '11.15 - 11.45',
                'nama_guru' => 'Keti Suyati, S.Pd',
                'bidang_studi' => 'B.Inggris',
                'Kelas' => 'VIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('gedmi_mapel')->insert($defaultData);
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('gedmi_mapel');
    }
}
