<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateGedmiUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('gedmi_user', function (Blueprint $table) {
            $table->id();
            $table->string('username')->unique();
            $table->string('password');
            $table->string('role');
            $table->timestamps();
        });

        $defaultData = [
            [
                'id' => 1,
                'username' => 'admin123',
                'password' => 'admin123',
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'username' => 'kepalasekolah',
                'password' => 'kepsek111',
                'role' => 'kepalasekolah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'username' => 'agung',
                'password' => 'agung123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'username' => 'almas',
                'password' => 'almas123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'username' => 'diana',
                'password' => 'diana123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'username' => 'erlina',
                'password' => 'erlina123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'username' => 'gaya',
                'password' => 'gaya123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'username' => 'hengki',
                'password' => 'hengki123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'username' => 'intan',
                'password' => 'intan123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'username' => 'jessica',
                'password' => 'jessica123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'username' => 'keti',
                'password' => 'keti123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'username' => 'sabdana',
                'password' => 'sabdana123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 13,
                'username' => 'salamauddin',
                'password' => 'salamuddin123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'username' => 'siti',
                'password' => 'siti123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'username' => 'tatang',
                'password' => 'tatang123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'username' => 'venny',
                'password' => 'venny123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'username' => 'purba',
                'password' => 'purba123',
                'role' => 'guru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 18,
                'username' => '22288170',
                'password' => '22288170',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'username' => '22288171',
                'password' => '22288171',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'username' => '22288172',
                'password' => '22288172',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'username' => '22288173',
                'password' => '22288173',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'username' => '22288174',
                'password' => '22288174',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'username' => '22288175',
                'password' => '22288175',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'username' => '22288176',
                'password' => '22288176',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'username' => '22288177',
                'password' => '22288177',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'username' => '22288178',
                'password' => '22288178',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'username' => '22288179',
                'password' => '22288179',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'username' => '22288180',
                'password' => '22288180',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'username' => '22288181',
                'password' => '22288181',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'username' => '22288182',
                'password' => '22288182',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'username' => '22288183',
                'password' => '22288183',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'username' => '22288184',
                'password' => '22288184',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'username' => '22288185',
                'password' => '22288185',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'username' => '22288186',
                'password' => '22288186',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'username' => '22288187',
                'password' => '22288187',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'username' => '22288188',
                'password' => '22288188',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'username' => '22288189',
                'password' => '22288189',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'username' => '22288190',
                'password' => '22288190',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 39,
                'username' => '22288191',
                'password' => '22288191',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'username' => '22288192',
                'password' => '22288192',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'username' => '22288193',
                'password' => '22288193',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'username' => '22288194',
                'password' => '22288194',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'username' => '22288195',
                'password' => '22288195',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'username' => '22288196',
                'password' => '22288196',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'username' => '22288197',
                'password' => '22288197',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'username' => '22288198',
                'password' => '22288198',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'username' => '22288199',
                'password' => '22288199',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id' => 48,
                'username' => '21288090',
                'password' => '21288090',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'username' => '21288091',
                'password' => '21288091',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'username' => '21288092',
                'password' => '21288092',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'username' => '21288093',
                'password' => '21288093',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'username' => '21288094',
                'password' => '21288094',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 53,
                'username' => '21288095',
                'password' => '21288095',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'username' => '21288096',
                'password' => '21288096',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'username' => '21288097',
                'password' => '21288097',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'username' => '21288098',
                'password' => '21288098',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'username' => '21288099',
                'password' => '21288099',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id' => 58,
                'username' => '21288100',
                'password' => '21288100',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'username' => '21288101',
                'password' => '21288101',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'username' => '21288102',
                'password' => '21288102',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'username' => '21288103',
                'password' => '21288103',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'username' => '21288104',
                'password' => '21288104',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'username' => '21288105',
                'password' => '21288105',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'username' => '21288106',
                'password' => '21288106',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'username' => '21288107',
                'password' => '21288107',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'username' => '21288108',
                'password' => '21288108',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'username' => '21288109',
                'password' => '21288109',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'username' => '21288110',
                'password' => '21288110',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'username' => '21288111',
                'password' => '21288111',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'username' => '21288112',
                'password' => '21288112',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'username' => '21288113',
                'password' => '21288113',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'username' => '21288114',
                'password' => '21288114',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'username' => '21288115',
                'password' => '21288115',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'username' => '21288116',
                'password' => '21288116',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'username' => '21288117',
                'password' => '21288117',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'username' => '21288118',
                'password' => '21288118',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'username' => '21288119',
                'password' => '21288119',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id' => 78,
                'username' => '20218005',
                'password' => '20218005',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'username' => '20218006',
                'password' => '20218006',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'username' => '20218009',
                'password' => '20218009',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'username' => '20218010',
                'password' => '20218010',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'username' => '20218011',
                'password' => '20218011',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'username' => '20218013',
                'password' => '20218013',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'username' => '20218014',
                'password' => '20218014',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'username' => '20218016',
                'password' => '20218016',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'username' => '20218017',
                'password' => '20218017',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'username' => '20218018',
                'password' => '20218018',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'username' => '20218019',
                'password' => '20218019',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'username' => '20218020',
                'password' => '20218020',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'username' => '20218021',
                'password' => '20218021',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'username' => '20218022',
                'password' => '20218022',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'username' => '20218023',
                'password' => '20218023',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'username' => '20218024',
                'password' => '20218024',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'username' => '20218025',
                'password' => '20218025',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'username' => '20218026',
                'password' => '20218026',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'username' => '20218027',
                'password' => '20218027',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'username' => '20218028',
                'password' => '20218028',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'username' => '20218029',
                'password' => '20218029',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'username' => '20218030',
                'password' => '20218030',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'username' => '20218031',
                'password' => '20218031',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'username' => '20218032',
                'password' => '20218032',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'username' => '20218033',
                'password' => '20218033',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'username' => '20218034',
                'password' => '20218034',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'username' => '20218035',
                'password' => '20218035',
                'role' => 'siswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('gedmi_user')->insert($defaultData);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('gedmi_user');
    }
}
